authapp/urls.py
from django.urls import path
from .views import *

app_name = "authapp"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("bloglist/", BlogListView.as_view(), name="bloglist"),
    path("blogcreate/", BlogCreateView.as_view(), name="blogcreate"),
    path("blog/<int:pk>/detail/", BlogDetailView.as_view(), name="blogdetail"),
    path("blog/<int:pk>/comment/",
         CommentCreateView.as_view(), name="commentcreate"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blogupdate"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blogdelete"),
    path("blog/<int:pk>/commentdelete/",
         CommentDeleteView.as_view(), name="commentdelete"),
    path("user/change/password/",
         PasswordChangeView.as_view(), name="passwordchange"),
    path("search/", SearchView.as_view(), name="search"),
    path("username-checker/", UsernameCheckerView.as_view(), name="usernamechecker"),
]

authproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authapp.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Blog(models.Model):
	title =	models.CharField(max_length=200)
	image = models.ImageField(upload_to="blogs")
	content = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title


class Comment(models.Model):
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	commenter = models.ForeignKey(User, on_delete=models.CASCADE)
	comment = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.commenter


SEMESTER = (
	("I", "First Semester"),
	("II", "II"),
	("III", "III"),
	("IV", "IV"),
)

class Course(models.Model):
	title = models.CharField(max_length=100)
	semester = models.CharField(max_length=50, choices=SEMESTER)

	def __str__(self):
		return self.title

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>User Management</title>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">
</head>
<body>
	{% if request.user.is_authenticated %}
		<h5>Logged in as <span style="color:blue"> {{request.user}} </span></h5>
		<a href="/logout/">Logout</a>
        <a href="{% url 'authapp:passwordchange' %}">Change Password</a>
	
	{% else %}
	<a href="/signup/">Signup</a>
	<a href="/login/">Login</a>

	{% endif %}
	<a href="{% url 'authapp:bloglist' %}">Blog List</a>
    
    <form method="GET" action="{% url 'authapp:search' %}">
        <input type="text" name="query">
        <button>Search</button>
    </form>
	

	{% block content %}
	{% endblock %}


<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>




<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [100, 200, 50, 80, 20, 10],
            backgroundColor: [
                'red',
                'rgba(54, 162, 235, 0.5)',
                'rgba(255, 206, 86, 0.5)',
                'rgba(75, 192, 192, 0.5)',
                'rgba(153, 102, 255, 0.5)',
                'rgba(255, 159, 64, 0.5)'
            ],
            borderColor: [
                'red',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
    {% block js %}

    {% endblock %}




</body>
</html>

templates/blogcreate.html
{% extends "base.html" %}
{% block content %}
	<h4>Create Blog</h4>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<button>Save</button>
	</form>
{% endblock %}

templates/blogdelete.html
{% extends "base.html" %}


{% block content %}

	<form method="POST">
		{% csrf_token %}
		Are You Sure?
		<button>Yes</button>
	</form>

{% endblock %}

templates/blogdetail.html
{% extends "base.html" %}
{% block content %}
	<li><h3>{{blogobject.title}}</h3></li>
	<img src="{{blogobject.image.url}}" width="500">
	<p>{{blogobject.content}}</p>
	<p>Created by: <span style="color: blue;">{{blogobject.author.username}}</span> at {{blogobject.date}}</p>


	<h3>{{blogobject.comment_set.all.count}} comment <span>on</span><label>{{blogobject.title}}</label></h3>
	{% for comment in blogobject.comment_set.all %}
		<h4>{{comment.commenter}}</h4>
		<h4>{{comment.date}}</h4>
		<p>{{comment.comment}}</p>
		<a href="{% url 'authapp:commentdelete' comment.pk %}">Delete</a>
		<hr>
	{% endfor %}
	<h3>Leave your comment</h3>
	<p>Please write your comment here...</p>
	<form method="POST" action="{% url 'authapp:commentcreate' blogobject.pk %}">
		{% csrf_token %}
		{{commentform.as_p}}
		<button>Comment</button>
	</form>
{% endblock %}

templates/bloglist.html
{% extends "base.html" %}
{% block content %}
	<h3> All Blogs</h3>
	{% for blog in allblog %}
		<li><h4><a href="{% url 'authapp:blogdetail' blog.id %}">{{blog.title}}</a></h4></li>
		<img src="{{blog.image.url}}" width="200">
		<p>Created by: <span style="color: blue;">{{blog.author.email}}</span> at {{blog.date|timesince}} ago</p>
		<a href="{% url 'authapp:blogupdate' blog.id %}">Update</a>
		<a href="{% url 'authapp:blogdelete' blog.id %}">Delete</a>
	{% endfor %}
{% endblock %}

templates/commentcreate.html
{% extends "base.html" %}
{% block content %}
	<h3>Create Comment</h3>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
	</form>
{% endblock %}

templates/commentdelete.html
{% extends "base.html" %}


{% block content %}
	<form method="POST">
		{% csrf_token %}
		<h3>Are you sure?</h3>
		<button>Yes</button>
	</form>

{% endblock %}

templates/error.html
{% extends "base.html" %}


{% block content %}
	<h3>Error: {{error}}</h3>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
	<h1>Welcome to home page</h1>
	<canvas id="myChart" width="400" height="400"></canvas>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
	<h4>Login Form</h4>
	{% if error %}
		<li>{{error}}</li>
	{% endif %}
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<button>Login Up</button>
	</form>
{% endblock %}

templates/passwordchange.html
{% extends "base.html" %}


{% block content %}
	{% if error %}
		<p>Error: {{error}}</p>
	{% endif %}
	<h3>Change Password</h3>
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<BUTTON>Change</BUTTON>
	</form>
{% endblock %}

templates/searchresult.html
{% extends "base.html" %}


{% block content %}
	<h3>Search Results</h3><hr>
	{% for blog in searched_blogs %}
		<li><a href="{% url 'authapp:blogdetail' blog.pk %}">{{blog.title}}</a></li>

		{% empty %}
		<h5>No results Found...</h5>

	{% endfor %}
{% endblock %}

templates/signup.html
{% extends "base.html" %}


{% block content %}

	<h4>Sign Up Form</h4>
	<form method="POST">
		{% csrf_token %}
		<p id="errorp"></p>
		{{form.as_p}}
		<button id="btn">Sign Up</button>
	</form>

{% endblock %}



{% block js %}
	
	<script type="text/javascript">
		$(document).ready(function() {
			// alert("Jquery worked");

			// $("#id_username").on("keyup", function() {
			// 	// alert("Keyup fucntion");
			// 	var a = $(this).val();
			// 	// var a = $("#id_username").val();
			// 	alert(a);
			// });

			$("#id_username").on("change", function() {
				// alert("Keyup fucntion");
				var a = $(this).val();
				// var a = $("#id_username").val();
				// alert(a);
				
				$.ajax({
					method: "get",
					url: "{% url 'authapp:usernamechecker' %}",
					data: {
						"uname":a,
					},
					success: function(data) {
						// alert("success");
						// alert(data.uname)
						if(data.response=="yes") {
							$("#errorp").text("Username not available");
							$("#errorp").css("color","red");
							$("#btn").attr("disabled","true");
						}
						else{
							$("#errorp").text("Username available");
							$("#errorp").css("color","green");
							$("#btn").removeAttr("disabled");
						}
							
					}
				})
			});

		})
	</script>

{% endblock %}